---
- hosts: cont16
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    inter_segment_fw_rule:  {"seq": 10,
                             "action": "next-hop",
                             "segment-interface": "web",
                             "dst": {"segment": "app", "tenant": "3-tier-app"},
                             "next-hop": {"next-hop-group": "ServiceNode"}}

    deny_segment_to_tenant:  {"seq": 15,
                              "action": "deny",
                              "segment-interface": "web",
                              "dst": {"segment": "qa", "tenant": "app-test"}}

    permit_any_to_any_rule: {"seq": 20, "action": "permit"}

  tasks:
    - name: bcf tenant
      bcf_tenant:
        name: 3-tier-app
        logical_router_interfaces: {'web': '10.0.0.1/24',
                                    'app':'10.0.1.1/24',
                                    'fw-01':'10.0.5.1/24'}
#        logical_router_system_tenant_interface: {'state':'present'}
        routes: {'0.0.0.0/0':'tenant:system'}
#        next_hop_groups: {'ServiceNode':'10.0.5.2'}
        policy_lists: {'Firewall': ['{{ inter_segment_fw_rule }}',
                                    #'{{ deny_segment_to_tenant }}',
                                    '{{ permit_any_to_any_rule }}']}
#        inbound_policy: Firewall
        controller: '{{ inventory_hostname }}'
        state: present
        access_token: cJHUJHGCGvXjOH_HaYJ3QgarRPVcv--5

    - name: bcf segment
      bcf_segment:
        name: web
        interface_groups: [ 'R1H1:untagged', 'R1H2:untagged' ]
        tenant: 3-tier-app
        controller: '{{ inventory_hostname }}'
        state: present
        access_token: cJHUJHGCGvXjOH_HaYJ3QgarRPVcv--5

    - name: bcf segment
      bcf_segment:
        name: app
        interface_groups: ['R2H1:untagged']
        tenant: 3-tier-app
        controller: '{{ inventory_hostname }}'
        state: present
        access_token: cJHUJHGCGvXjOH_HaYJ3QgarRPVcv--5

    - name: bcf segment
      bcf_segment:
        name: fw-01
        interface_groups: ['FW-01:untagged']
        tenant: 3-tier-app
        controller: '{{ inventory_hostname }}'
        state: present
        access_token: cJHUJHGCGvXjOH_HaYJ3QgarRPVcv--5
